
Drop DATABASE  If Exists base
GO 

Create Database base
Go

USE base
GO

Create table RESTAURANT (
    ID Int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CITY VARCHAR(50),
    ADRESS VARCHAR(100),
    RESTAURANTADD VARCHAR(100) ,
)
GO

GO


Create table EMPLOYE(
    ID Int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    SURNMAE VARCHAR(50) ,
    PERSID VARCHAR(11),
)
GO

CREATE TABLE EMPLOYE_ROLES (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) ,
);
GO


Create table TYPEM (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    title VARCHAR(50) ,
);
GO

Create table MEAL (
    ID Int IDENTITY(1,1) NOT NULL, 
    NAME VARCHAR(50) NOT NULL,
    TYPEID INT NOT NULL,
    FOREIGN KEY (TYPEID) REFERENCES TYPEM(ID)
)
GO

Create table RESERVATION (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RESID INT,
    SURNAME VARCHAR(50),
    RESERVDATETIME DATETIME,
    PHONE VARCHAR(18),
    NUMBOFGUEST INT,
    FOREIGN KEY (RESID) REFERENCES RESTAURANT(ID)
)

GO
CREATE TABLE RESTAURANT_EMPLOYE (
    RESID INT NOT NULL,
    EMPID INT NOT NULL,
    ROLEID INT NOT NULL,
    PRIMARY KEY (RESID, EMPID),
    FOREIGN KEY (RESID) REFERENCES RESTAURANT(ID),
    FOREIGN KEY (EMPID) REFERENCES EMPLOYE(ID),
    FOREIGN KEY (ROLEID) REFERENCES EMPLOYE_ROLES(ID)
);
GO











